### ISSUE TITLE
NoMethodError (undefined method `object' for nil:NilClass Did you mean?  object_id):

### ISSUE THREAD

**Issue by ratneshnavlakhe** [sorentwo/carrierwave-aws#100]
Getting this issue while upload..
Please help

**Comment by sorentwo** [comment]
There isn't nearly enough detail in your report for me to try and help. Perhaps with a stacktrace and some sort of context I can provide information.

**Comment by ratneshnavlakhe** [comment]
Issue resolved, was not setting environment variables.

**Comment by raunakkumar55** [comment]
@ratneshnavlakhe I am facing same issue on remote server, On local, it works fine. What environment variables are you referring to?
