### ISSUE TITLE
Tautological test?

### ISSUE THREAD

**Issue by atz** [sorentwo/carrierwave-aws#103]
Does this test capture the intent? 
https://github.com/sorentwo/carrierwave-aws/blob/a832b01964c37da6fa3f723308c6807e87394d15/spec/carrierwave/storage/aws_spec.rb#L26
```ruby
    it 'caches connections by credentials' do
      expect(storage.connection).to eq(storage.connection)
    end
```

That seems like it could never usefully fail and does not demonstrate caching, compared to:

```ruby
expect(storage.connection).to eq CarrierWave::Storage::AWS.new(uploader).connection
```

**Comment by sorentwo** [comment]
If I recall it was lifted from the corresponding Fog code in `carrierwave` proper. A PR to make the intent clearer, and demonstrate that the connection is cached would be welcome.

**Comment by atz** [comment]
I suspect what happened is that they broke out the constructor call to the `let(:storage)` statement and search-replaced everywhere it had been, overlooking the fact that second call on the line *intended* to get a different object.

**Comment by sorentwo** [comment]
A more meaningful spec has been added with  4a2e18d
