### ISSUE TITLE
Handle timeouts

### ISSUE THREAD

**Issue by cmalpeli** [sorentwo/carrierwave-aws#107]
Is there a built in way to handle/set a timeout in the scenario where the underlying storage provider is unavailable?

**Comment by sorentwo** [comment]
There aren't any facilities within CarrierWave that I'm aware of, but aws-sdk may have something if you check their docs. There are known issues with using the `Timeout` module, and even `Rack::Timeout`, so I'm not sure what I'd suggest for handling it manually either.
