### ISSUE TITLE
When acl is set to private, it doesn't use asset_host parameter

### ISSUE THREAD

**Issue by andricicezar** [sorentwo/carrierwave-aws#108]
If `aws_acl` is set to public-read, the link generated for download is created based on `asset_host` parameter, and not the endpoint, which is the expected behavior.

If  `aws_acl` is set to private, the link generated for download is created based on the endpoint parameter, not on `asset_host` parameter, which is not the expected behavior.

I did something wrong, or this is how it is supposed to work?

### Config file
```
  CarrierWave.configure do |config|
    config.storage    = :aws
    config.aws_bucket = "assets"
    config.aws_acl    = "private"

    config.asset_host = 'http://example.com'

    config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7

    config.aws_attributes = {
      expires: 1.week.from_now.httpdate,
      cache_control: 'max-age=604800'
    }

    config.aws_credentials = {
      access_key_id:     "...",
      secret_access_key: "...",
      region:            "...",
    }


    Aws.config[:s3] ={
     endpoint: 'http://internal-link',
      force_path_style: true
    }
  end
```

**Comment by sorentwo** [comment]
You haven't configured anything wrong, that is the way the URL is generated when the ACL is private. Truthfully I don't remember why this is the case. The logic was based on what the Fog client did and I didn't really question it however many years ago.

If you're willing to experiment with using the asset host for private URLs I'd welcome a PR.

**Comment by cmalpeli** [comment]
@andricicezar did you ever figure this out?

**Comment by mftaff** [comment]
@andricicezar @cmalpeli 
I am looking into the same issue? Have either of you come solved this?
Thanks!!

**Comment by andricicezar** [comment]
@mftaff no

**Comment by cmalpeli** [comment]
@mftaff me neither.
