### ISSUE TITLE
Support for Minio

### ISSUE THREAD

**Issue by vovimayhem** [sorentwo/carrierwave-aws#110]
Is there any way to configure the S3 Host and the S3 Endpoint? We're giving a try with Minio (a storage service compatible with S3 clients - see https://minio.io) + Carrierwave, and using fog-aws we could configure Carrierwave to use our private service instead of Amazon S3: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Use-minio-with-Carrierwave

Is this possible with carrierwave-aws?

**Comment by sorentwo** [comment]
We rely entirely on aws-sdk-ruby to interface with S3. A quick search turned up these docs on using minio with aws-sdk: https://docs.minio.io/docs/how-to-use-aws-sdk-for-ruby-with-minio-server. It looks like you can set the `endpoint` with `Aws.configure` outside of the CarrierWave configuration block.

Hope that helps!
