### ISSUE TITLE
undefined method `eager_autoload!' for Aws:Module

### ISSUE THREAD

**Issue by lepfhty** [sorentwo/carrierwave-aws#112]
i am using aws-sdk 2.0.46 and getting this error when upgrading to carrierwave-aws 1.1.0

the dependency on aws-sdk should probably be `~> 2.1` rather than the current value of `~> 2.0`

eager autoloading was introduced in 2.1.0:
https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md#210-2015-06-11

**Comment by sorentwo** [comment]
Nice find. I'm surprised this hasn't come up before. Would you please open a PR?

**Comment by sorentwo** [comment]
Closed with #113
