### ISSUE TITLE
Image upload not appearing in AWS console

### ISSUE THREAD

**Issue by devinma66** [sorentwo/carrierwave-aws#117]
When my users upload images through this gem, the image appears on the website via Cloudfront CDN delivery but when I look at the AWS console, it's not there in the bucket. Does it have to do with my initializer settings? I'm new to AWS and any help will be appreciated!

```ruby
CarrierWave.configure do |config|
  config.storage    = :aws
  config.aws_bucket = ENV.fetch('S3_BUCKET_NAME')
  config.aws_acl    = 'public-read'

  config.asset_host = 'https://example.cloudfront.net'

  config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7

  config.aws_attributes = {
    expires: 1.week.from_now.httpdate,
    cache_control: 'max-age=604800'
  }
end
```
Also, can someone explain what `aws_authenticated_url_expiration` means? The comment isn't making sense to me.

**Comment by sorentwo** [comment]
There isn't enough information here to determine where the file is being stored. That would depend on the `store_dir` and `filename` within each of your uploaders.

The `aws_authenticated_url_expiration` is what determines how long an authorized URL is valid. It only applies to private objects, and you have your `aws_acl` configured to `public-read`, so it doesn't apply to you.
