### ISSUE TITLE
Setting Cache-Control and Expires headers on files uploaded to s3

### ISSUE THREAD

**Issue by gaganawhad** [sorentwo/carrierwave-aws#12]
Is there a way I can set the expires header on files uploaded to s3 using carrierwave-aws

**Comment by musaffa** [comment]
@sorentwo This feature should be documented in the `readme`.

**Comment by sorentwo** [comment]
@musaffa: I agree, it's a common use case. I'm happy to accept a PR, otherwise I'll include them in the docs within the next week or so.

**Comment by sorentwo** [comment]
Never mind, just dropped it in there with c587712
