### ISSUE TITLE
Cannot find module 'aws/s3' on load

### ISSUE THREAD

**Issue by slalomandrew** [sorentwo/carrierwave-aws#120]
When trying to use this tool (which looks great, by the by), I get the above error on the following line. 

~/.rvm/gems/ruby-2.3.4/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:1:in `require': cannot load such file -- aws/s3 (LoadError)

Is this a result of loading things out of order? I feel like I'm doing something wrong.

**Comment by sorentwo** [comment]
Will you share the spec you are using in your Gemfile? That looks like a very old version of carrierwave-aws.

**Comment by slalomandrew** [comment]
Indeed, I'd been using the default. When I forced 1.2, I got clashes with aws-sdk version 3, which was also in the project. I can downgrade my aws sdk version for now and hope that it works out.

**Comment by sorentwo** [comment]
Please give master a try and see if that works for you. It uses the new s3 specific gem, rather than the full aws-sdk.

**Comment by slalomandrew** [comment]
Seems to work - I'm getting an issue with what appears to be region mismatch, though. My bucket lives in us-west-2, and I'm setting that in carrierwave.rb: 

```
  REGION = ENV.fetch 'AWS_REGION', 'us-west-2'
  config.aws_credentials = { region: REGION }

```

But getting

`Aws::S3::Errors::PermanentRedirect - The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.:`

**Comment by sorentwo** [comment]
You can specify a SHA, but I went ahead and release `1.3.0` with the updated version.

The `public/uploads` issue isn't related to the gem version, that's just standard CarrierWave test mode stuff.

**Comment by slalomandrew** [comment]
Thanks, you're the man.

**Comment by sorentwo** [comment]
Master uses the `aws-sdk-s3` gem directly, I don't believe this is still a problem. Closing.

**Comment by muhammadyana** [comment]
Hello i get some error 
`cannot load such file -- aws/s3 (LoadError)`

and my gemfile 
`gem 'carrierwave', '~> 2.0'`
`gem 'carrierwave-aws'
`

thanks
