### ISSUE TITLE
File size is 0 after upload

### ISSUE THREAD

**Issue by overovermind** [sorentwo/carrierwave-aws#121]
We are using this great gem for our connection with aws. However, sometimes (about 1% of the time) the file size is 0 but the file is uploaded with name, path and aws_acl rights.

As we didn't see this in the development environment (local storage) or with fog connection, could it be an issue with the aws-connection?

Thanks for the gem and keep up the great work!

**Comment by sorentwo** [comment]
This is the first I've heard of the issue and not something I've experienced myself. The primary application this gem was developed for and used with has tens of millions of uploads and I haven't seen this there.

It definitely could be an issue with the aws connection, but I'm rather confident it would be an issue within `aws-sdk`, and not something within `carrierwave-aws`. Perhaps try the most recent version with the latest `aws-sdk-s3` gem and see if the problem persists.
