### ISSUE TITLE
Get public url for an item uploaded using authenticated read

### ISSUE THREAD

**Issue by manojmj92** [sorentwo/carrierwave-aws#122]
I am uploading photos using AvatarUploader which has configured `self.aws_acl = 'authenticated-read'`

As a result, all the urls generated have expiry tokens.
However, for a specific case, I need to get the public url (this should not expire) for an object.
However calling `object.image.url` always gives links that will expire.

Is there a way to get a public url even though the `aws_acl` is set as `authenticated_read`. Can we override this on a per method basis or something?

**Comment by sorentwo** [comment]
You can override the `aws_acl` on an uploader class basis, but not for a specific record or uploader instance. If there is a particular S3 object that you need to generate a link to and you're willing to special case it in your code you can use the `public_url` method directly: `avatar.file.public_url`.

That will generate the URL, but it won't guarantee that the ACL is actually public. Hope that helps!

**Comment by manojmj92** [comment]
Thanks @sorentwo !
