### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by catalinabustam** [sorentwo/carrierwave-aws#124]
When file name contain characters in Spanish (ñ, á, é ...) this encode error occurs when calling **url** or  **filename** methods:

`incompatible character encodings: ASCII-8BIT and UTF-8`

After upgrade from 1.0.0 to 1.3.0

Thank you in advance

**Comment by sorentwo** [comment]
I'm not able to recreate this in the test suite with the information you've provided. Can you provide more details about when this happens, perhaps provide an example or a failing test case?

**Comment by catalinabustam** [comment]
An user uploads a file named  **niño.jpg**

then when it is called from a view:

`= link_to attachment.file.filename, attachment.url, target: '_blank'`

we have the error:

`incompatible character encodings: ASCII-8BIT and UTF-8`

That is what I get from terminal `file.filename`:   **ni\xC3\xB1o.jpg**

**Comment by sorentwo** [comment]
What database is it being stored in? What version of Ruby are you using?

**Comment by catalinabustam** [comment]
ruby 2.3.0
rails 4.2.9
PostgreSQL 9.5.7

**Comment by sorentwo** [comment]
I don't see anything telling in the Ruby or Postgres version. It would be really helpful to have a failing test case that showed this issue. Can you write one for the `carrierwave-aws` test suite?
