### ISSUE TITLE
stream aws s3 files with application url

### ISSUE THREAD

**Issue by anklos** [sorentwo/carrierwave-aws#126]
Hi there,

I don't want user to access S3 files with temporary url, rather I need user to have login session to access file with my application url. Is there any way I can configure this gem to make it stream private S3 file content to my application server, then render it to client?

Many thanks!

**Comment by sorentwo** [comment]
No, there isn’t any built in way to do this. I would strongly recommend d against it as well—Ruby doesn’t handle multiple concurrent connections very well. On the other hand, S3 is perfectly suited to serving millions of files concurrently and will respect the permissions you set.

**Comment by janko-m** [comment]
@anklos You can use the `aws-sdk-s3` gem directly for that:

```rb
resource = Aws::S3::Resource.new(
  access_key_id: "my-key",
  secret_access_key: "my-secret",
  region: "my-region",
)

bucket = resource.bucket("my-bucket")

object = bucket.object(object_key) # this is probably the CarrierWave filename

object.get do |chunk|
  # streaming
end
```

In a Rails controller you could assign a chunks enumerator for the response body:

```rb
class FilesController < ApplicationController
  def show
    # ... retrieve S3 object ...

    self.response_body = object.enum_for(:get)
  end
end
```

Also, you might want to take a look at Shrine's [`rack_response`](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/rack_response.rb) implementation to see which response headers should be assigned (e.g. `Content-Length`, `Content-Type`), and how to support [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

**Comment by sorentwo** [comment]
I’ll take this opportunity to say: listen to Janko, he definitely knows more than me. Also, if you aren’t locked into Carrierwave you should *definitely* use Shrine instead.

**Comment by anklos** [comment]
i have been using carrierwave-aws gem in my codebase for a few years and very happy about it, so I was thinking if there is a way to configure it for the new requirement.

Thank you guys, really appreciate your help!

**Comment by anklos** [comment]
@sorentwo i thought the streaming is the only way to achieve it. in your comment ` On the other hand, S3 is perfectly suited to serving millions of files concurrently and will respect the permissions you set.`, is there another way that s3 files can hide behind Rails login session, rather than stream the content to my application server and render it to client.

Thanks!

**Comment by balbesina** [comment]
you can download the file directly from carrierwave-aws:
```ruby
aws_file = your_record.your_file_attribute.file
aws_s3_object = aws_file.file
aws_s3_object.get do |chunk|
  response.stream.write chunk
end
```

**Comment by tscholz** [comment]
See https://github.com/sorentwo/carrierwave-aws/blob/20e58da928894f2b2b835ab58011745718fd5c02/lib/carrierwave/storage/aws_file.rb#L48

You can use
```
model.file_attr.read do |chunk|
  response.stream.write chunk
end
```
