### ISSUE TITLE
Request has expired

### ISSUE THREAD

**Issue by mahabib** [sorentwo/carrierwave-aws#137]
I have the following config for **URL expiration** and **caching**.

```
  config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7
  config.aws_attributes = {
    expires: 1.week.from_now.httpdate,
    cache_control: 'max-age=604800'
  }
```

  As per my understanding, everytime a new request is made with `.url` a new authenticated URL gets generated.
  But I am getting Request has expired message when requesting a file.

  Is it because of the cache?
  Is there a way to clear the cache?

**Comment by mahabib** [comment]
@sorentwo Please have a look at the issue, that will be a great help.

Following is the response I'm getting when making a request.

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  <X-Amz-Expires>604800</X-Amz-Expires>
  <Expires>2018-11-14T18:50:38Z</Expires>
  <ServerTime>2018-11-26T06:09:57Z</ServerTime>
  <RequestId>3508CC521EE70FC8</RequestId>
  <HostId>
    zORuBb9/ogc6nmSQg5dg7NX5MmrfPkn/UJO7h8/2I++97F2030O0mpBkaAkuvWlh6GKQ6KIHJOo=
  </HostId>
</Error>
```

Errors are not coming for all links, it's happeing for few links.

**Comment by sorentwo** [comment]
Every call to .url generates a fresh URL. You won’t get fresh expirations if you are caching the generated URL. If you must cache then be sure the cache expires before the URL. For example, set the cache TTL to 6 days and the S3 expiration to 7.

**Comment by mahabib** [comment]
@sorentwo Thanks a lot.

Disabled the cache for time being.

Is there a way to clear the cache for my old entries?

**Comment by sorentwo** [comment]
I’m not sure how or what you are caching, so that is difficult to answer. If you have disabled the cache then old data shouldn’t be an issue.

**Comment by mahabib** [comment]
> Every call to .url generates a fresh URL. You won’t get fresh expirations if you are caching the generated URL. If you must cache then be sure the cache expires before the URL. For example, set the cache TTL to 6 days and the S3 expiration to 7.

@sorentwo Got the point. Really appreciated the help.

Now I've updated the config,
```
config.aws_attributes = {
  expires: 5.day.from_now.httpdate,
  cache_control: 'max-age=432000'
}
```

> I’m not sure how or what you are caching, so that is difficult to answer. If you have disabled the cache then old data shouldn’t be an issue.

This is just for my curiosity.
Let's assueme, caching is happening and I want to remove them, is there a way to do that?
I tried this but didn't work for me, `CarrierWave.clean_cached_files!`

**Comment by sorentwo** [comment]
I’m referring to view level caching, not upload caching. Upload caching is part of how carrierwave works and has nothing to do with caching URLs.

**Comment by mahabib** [comment]
@sorentwo 

> Every call to .url generates a fresh URL. You won’t get fresh expirations if you are caching the generated URL. If you must cache then be sure the cache expires before the URL. For example, set the cache TTL to 6 days and the S3 expiration to 7.

The above I tried still same error. 
Below is my carrierwave config,
```
CarrierWave.configure do |config|
	config.delete_tmp_file_after_storage = false
	config.storage    = :aws
	config.aws_bucket = 'mybucket'
	config.aws_acl    = 'private'


	# The maximum period for authenticated_urls is only 7 days.
	config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7

	# Set custom options such as cache control to leverage browser caching
	config.aws_attributes = {
		expires: 6.day.from_now.httpdate,
		cache_control: 'max-age=432000' # 5 days
	}

	config.aws_credentials = {
		access_key_id:     ******,
		secret_access_key: ******,
		region:            'ap-southeast-1'
	}
end
```

Still getting same error,
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  <X-Amz-Expires>604800</X-Amz-Expires>
  <Expires>2018-11-30T10:18:03Z</Expires>
  <ServerTime>2018-12-05T01:36:38Z</ServerTime>
  <RequestId>1A85A3D1D43A184A</RequestId>
  <HostId>
    Nxppu+cpTlkQjPS2rVPlcfYtrgkqR9v7MjDSSL5Nx3VA+WzlyeATVFS+kaQT8p66e1CKqtffxUw=
  </HostId>
</Error>
```

I'm stuck here. Can you please have a look.

**Comment by sorentwo** [comment]
The difference between the expiration and server time is quite drastic. Have you verified that your server’s clock is correct?
