### ISSUE TITLE
Not working with recommended bucket policy

### ISSUE THREAD

**Issue by djalmaaraujo** [sorentwo/carrierwave-aws#140]
Aws::S3::Errors::AccessDenied in Admin::ApurationsController#create

- I keep getting S3 permission denied

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::tradertax-files",
            "Principal": {
                "AWS": "XXX"
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::tradertax-files/*",
            "Principal": {
                "AWS": "XXX"
            }
        }
    ]
}
```

I already restarted, added correct credentials, add my user as root even, and this policy is not working. ideas?

**Comment by sorentwo** [comment]
Can you share your carrierwave configuration, and, if you're overriding inside the uploader, that configuration as well?

**Comment by genail** [comment]
To anyone still having a similar issue: By default, S3 buckets are blocking put-object request with public-read ACL. If you're getting access denied errors despite valid configuration, make sure to check your S3 bucket Permissions tab and uncheck these two:

![image](https://user-images.githubusercontent.com/113201/51333276-ac921600-1a7d-11e9-83ab-ebb98d127c7a.png)
