### ISSUE TITLE
Change example aws_acl to private

### ISSUE THREAD

**Issue by LeKristapino** [sorentwo/carrierwave-aws#143]
It seems that example code `aws_acl` parameter should set to `private`, since by default AWS S3 ACL settings for public ACL are set to false.  This results in `Access Denied` error when simply creating a bucket and using sample code. 

It also seems that something has changed in AWS S3 enforcement of these restrictions in the past couple of days, because I have 2 accounts where S3 buckets were created 5 days apart, running the same application with exactly the same settings - in latest one I always get `Access Denied` with `public-read-write` ACL, in the older one everything works - hence the suggestion :)

**Comment by sorentwo** [comment]
Fair point, `private` is a smarter default anyhow since most people copy and paste the entire example. Would you mind opening a PR?

**Comment by sorentwo** [comment]
Never mind, I made the small change. Thanks for reporting it 👍
