### ISSUE TITLE
store! gets stuck

### ISSUE THREAD

**Issue by chadwilken** [sorentwo/carrierwave-aws#144]
After a bit of debugging when I call the `store!` method on a video file it would hang indefinitely and spike the CPU usage to 100%, any ideas what would cause that?

**Comment by sorentwo** [comment]
Spiking the CPU like that sounds like a video processing issue, not something coming from carrierwave-aws or aws-s3 itself. I suggest experimenting with different video sizes, and if you have any video processing enabled (e.g. capturing thumbnails, re-encoding) try disabling that.

If you find that the issue continues I suggest opening an issue with https://github.com/aws/aws-sdk-ruby directly.

**Comment by chadwilken** [comment]
It turned out that someone was uploading video as a document and it was messing up when trying to process that, you're spot on!
