### ISSUE TITLE
Aws::Sigv4::Errors::MissingCredentialsError

### ISSUE THREAD

**Issue by hupadhyayula** [sorentwo/carrierwave-aws#147]
When I try to upload an image using `carrierwave-aws` locally it works just fine. However, when I try it on production, getting the following error.  I have everything setup correctly, because it works on my dev environment, but on production it's not working.

Dev and Prod running on Ubuntu/Bionic

```
Message
Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider
```

Gemfile

```
gem 'carrierwave-aws'
```

config/initializers/carrierwave.rb
```
CarrierWave.configure do |config|
  config.aws_bucket = Figaro.env.aws_s3_bucket_name
  config.aws_acl    = 'public-read'
  config.aws_authenticated_url_expiration = 60 * 60 * 24
  config.aws_credentials = {
    access_key_id:     Figaro.env.aws_access_key_id,
    secret_access_key: Figaro.env.aws_secret_access_key,
    region:            Figaro.env.aws_s3_region
  }
  config.asset_host = "https://s3.amazonaws.com/#{Figaro.env.aws_s3_bucket_name}"
end
```

**Comment by hupadhyayula** [comment]
I edited `config/initializers/carrierwave.rb` file on production and hard coded the values to test, still doesn't work for some reason. 
I got in to `rails console` and tried to do the following 
`CarrierWave::Uploader::Base.aws_credentials` and it gives me all the right values.

**Comment by hupadhyayula** [comment]
Well, I restarted my Puma server and it started working. For future reference

`sudo systemctl stop puma`
`sudo systemctl start puma`

**Comment by sorentwo** [comment]
Glad you figured it out!
