### ISSUE TITLE
Version bump for Carrierwave 2.0

### ISSUE THREAD

**Issue by gaffneyc** [sorentwo/carrierwave-aws#150]
Since carrierwave 2.0 has been released bundler is locking to carrierwave-aws 0.4.1 since it did not have an upper level version constrain applied.

It looks like this was fixed a couple weeks ago but we need a new version published to rubygems.

**Comment by sorentwo** [comment]
Thanks for the reminder! I've [released v1.4.0](https://rubygems.org/gems/carrierwave-aws/versions/1.4.0)—just shy of *two years* after v1.3.0.

**Comment by gaffneyc** [comment]
Thanks!

**Comment by Kukunin** [comment]
There is Carrierwave 2.1.0 and constraints don't allow it again =(
