### ISSUE TITLE
Carrierwave / AWS S3 Upload Endpoints

### ISSUE THREAD

**Issue by aximuseng** [sorentwo/carrierwave-aws#152]
https://stackoverflow.com/questions/58457036/carrierwave-aws-s3-upload-endpoints

I have a Rails app that I am migrating to a new server.  The existing server uses Carrierwave to upload to S3.  I am using:

    gem 'carrierwave'
    gem 'carrierwave-aws'
    gem 'cloudfront-signer'

The existing server works fine and I can upload.  The buckets on that one are `us-west-2`.  The new server returns this when I upload:

> Aws::S3::Errors::PermanentRedirect: The bucket you are attempting to
> access must be addressed using the specified endpoint. Please send all
> future requests to this endpoint.

This server is in `ca-central-1` (Canada).  I have doubled checked the settings.  The only difference is the region.

Here is my CW config - this is the same on both servers.

      config.aws_attributes = {
       expires: 10.minutes.from_now.httpdate,
       cache_control: 'max-age=600'
      }
    
      config.aws_credentials = {
        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        region: ENV['AWS_REGION']
      }
       
      config.enable_processing = true
      config.aws_signer = -> (unsigned_url, options) { Aws::CF::Signer.sign_url unsigned_url, options }
      config.storage = :aws
      config.cache_storage :aws
      config.aws_bucket = ENV['AWS_BUCKET']
      config.asset_host = ENV['CLOUDFRONT_HOST']
      config.aws_acl = :private

The carrierwave-aws GEM page has some settings for the endpoint but none of these work.

Any ideas?

**Comment by aximuseng** [comment]
I am going crazy. My old deploy was using the 1.0.0 version of carrierwave. Tried rolling that back - no luck.

I even tried using the old server region and bucket. Same error message.

**Comment by sorentwo** [comment]
I would guess that there is a mismatch between the `AWS_REGION` and your `CLOUDFRONT_HOST`, but that is just a guess. Since this was working before it seems like this is purely an AWS / Config issue and not a bug coming from carrierwave-aws.

**Comment by aximuseng** [comment]
That’s the crazy part.  I have tested it with the same region / keys / settings as the existing server that works - I still get the same error. Both are using the same cloud front host etc.  I am just hoping someone out there may have seen this issue before.

**Comment by aximuseng** [comment]
I am going to close this.  I went through line by line and manually entered the config values vs vis ENV.  It worked.  Put the ENV back in and still works.  No idea - must have been a typo on my end somewhere.

**Comment by sorentwo** [comment]
Glad you figured it out :+1:

**Comment by aximuseng** [comment]
It cropped up again - it seems to be:

`config.cache_dir = "#{Rails.root}/tmp/"`

**Comment by aximuseng** [comment]
Ready to give up at this point and try fog again.  The issue persists. It's not related to CloudFront.  I can't upload to the non-standard region at all.

**Comment by aximuseng** [comment]
Same error:

> Aws::S3::Errors::PermanentRedirect: The bucket you are attempting to
> access must be addressed using the specified endpoint. Please send all
> future requests to this endpoint.

```
  config.aws_attributes = {
   expires: 10.minutes.from_now.httpdate,
   cache_control: 'max-age=600'
  }

  config.aws_credentials = {
    access_key_id: 'XXXXX',
    secret_access_key: 'YYYYYY',
    region: 'ca-central-1',
    endpoint: 'https://s3.ca-central-1.amazonaws.com'
  }

   config.enable_processing = true
   config.storage = :aws
   config.aws_acl = :private
```

**Comment by aximuseng** [comment]
So I have a hunch - I suspect that the region is not being passed to AWS.  Under my AWS console in the IAM section there is the list of access keys.  It shows the last access.  My old set-up was under us-west-2.  When I was getting these errors this would report the last region call as us-west-1 (the default region) and not ca-central-1.

**Comment by aximuseng** [comment]
I switched to FOG and it works with the same configuration.

**Comment by aximuseng** [comment]
What a mess - I had a bucket setting in another uploaded that was triggering this.  I was so focused on the uploaded that was failing that I didn't realize that was the issue. 🤦‍♂️
