### ISSUE TITLE
Url returns nill for versions uploaded in background

### ISSUE THREAD

**Issue by ahmedrayhan** [sorentwo/carrierwave-aws#160]
Here is my code for the uploader
```

  version :large, if: :delayed_store? do
    process convert: 'jpg', if: :not_jpg?
    process resize_to_fill: [750, 625]
  end

  def delayed_store?(img = nil)
    !! @delayed_store
  end

  def delayed_store=(value)
    @delayed_store = value
  end
```
I am uploading this version with sidekiq and it works fine. The problem is if when I try to retrieve this version in the view it gives me nill error for the URL.

**Comment by sorentwo** [comment]
Sorry, this doesn't appear to be a carrierwave-aws specific issue. Between concurrency with sidekiq, your storage, permissions and carrierwave in general it is outside of this gem's area.
