### ISSUE TITLE
Release new version for Carrierwave 2.1

### ISSUE THREAD

**Issue by gaffneyc** [sorentwo/carrierwave-aws#162]
Would it be possible to release a new version since 384d95f8cefe2d25e1168feff81c257ac7b8387c fixes version matching for carrierwave 2.1?

On another note, it might be worth switching the match to `~> 2.0` or `< 3` or just removing the constraint since it's unlikely they'll break the API with a minor version.

**Comment by sorentwo** [comment]
Done! `v1.5.0` is released.

**Comment by gaffneyc** [comment]
Thank you!
