### ISSUE TITLE
supports DigitalOcean Spaces?

### ISSUE THREAD

**Issue by dvodvo** [sorentwo/carrierwave-aws#168]
[sorry for querying here]

I've been searching for some confirmation regarding applicability of `carrierwave-aws` with DO Spaces.
Given DO uses AWS underneath, it is a pretty valid assumption, but an assumption nonetheless.

Any information, confirmations, limitations to put forth?

**Comment by sorentwo** [comment]
@dvodvo Sorry, I have no idea. This gem builds entirely on `aws-sdk`, so if DO works with `aws-sdk` then it will work.
