### ISSUE TITLE
Compatibility with mobile browsers

### ISSUE THREAD

**Issue by michaelvli** [sorentwo/carrierwave-aws#35]
Thanks for developing this gem.  I've been using it to upload video files onto my Amazon S3 account.  Recently, I've tried to upload videos from my iPhone browser (Chrome and Safari) to Amazon as well but for some reason, the size of the uploaded file in my S3 bucket is 0 bytes (yes, the name of the file is successfully created).  

Can you tell me Carrierwave is capable of uploading files stored on iOS to Amazon S3?  I'm wondering if the contents of the file aren't uploading because Carrierwave isn't able to upload the file in a temporary directory on iOS (the way it does for for desktop browsers) in order to validate the file prior to sending to Amazon.  Thanks!

**Comment by sorentwo** [comment]
The browser used to upload files to carrierwave won't matter. It's all abstracted as a rack upload, so it isn't related to carrierwave itself, and certainly not carrierwave-aws.

You'll need to check some intermediate points during the upload to see where things are going south.
