### ISSUE TITLE
carrierwave-aws doesn't append bucket name to the host URL

### ISSUE THREAD

**Issue by vassyz** [sorentwo/carrierwave-aws#37]
fog gem config:
```
config.fog_credentials = {
  :host => 's3-eu-west-1.amazonaws.com'
}
config.fog_directory  = 'mybucket'
```
carrierwave-aws config:
```
config.aws_bucket = 'mybucket'
config.asset_host = 'https://s3-eu-west-1.amazonaws.com/mybucket'
```
Shouldn't this be kept a bit more consistent?

**Comment by sorentwo** [comment]
Perhaps the means for configuring fog has changed. Very little was changed intentionally, as noted in the README:

> The only notable difference is the use of aws_bucket instead of fog_directory, and aws_acl instead of fog_public.

I'd rather not change the existing config on carrierwave-aws just to match fog though, if that has indeed changed. Thank you for the consideration.
