### ISSUE TITLE
undefined method `download_url' 

### ISSUE THREAD

**Issue by l3iodeez** [sorentwo/carrierwave-aws#38]
Somewhat new to Rails I had trouble making Fog work with S3 so I installed this gem. Uploading works fine but I am having trouble making my download links work. My model is Reports.

reports_controller.rb:

<code>
      def download
      redirect_to download_url(@report.filename)
      end
<./code>

reports_uploader.rb

<code>
 def download_url(filename)
      url(response_content_disposition: %Q{attachment; filename="#{filename}"})
  end
<./code>

carrierwave.rb

<code>
  CarrierWave.configure do |config|
  config.storage    = :aws
  config.aws_bucket = ENV.fetch('AWS_BUCKET_NAME')
  config.aws_acl    = :public_read
  config.asset_host = 'http://myproject.herokuapp.com'
  config.aws_authenticated_url_expiration = 600
   config.aws_credentials = {
    access_key_id:     ENV.fetch('AWS_ACCESS_KEY_ID')}
    config.aws_credentials = {
    secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY') 
     }
end
<./code>

when I click the download link I get the error "undefined method `download_url' for #<ReportsController:0xb30787f4>"

Thanks!

**Comment by sorentwo** [comment]
You've only defined the `download_url` method in the Uploader, not in the Controller. You just need to move it into the `reports_controller.rb`:

```ruby
def download
  redirect_to download_url(@report.filename)
end

private

def download_url(filename)
  url(response_content_disposition: %Q{attachment; filename="#{filename}"})
end
```
