### ISSUE TITLE
How can I set my aws directory https://s3.amazonaws.com/xxx so I can show the image in the View

### ISSUE THREAD

**Issue by ballin22s** [sorentwo/carrierwave-aws#39]
def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
end

**Comment by sorentwo** [comment]
This isn't specific to carrierwave-aws at all, it's purely a carrierwave and rails issue. Please check the documentation for carrierwave to see how `url` helpers work.
