### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by Kukunin** [sorentwo/carrierwave-aws#40]
My bucket is in the us-west-1 region, and it is available via special endpoint. It seems, there is no way to set the custom endpoint in the configuration. I had to monkey patch the gem:

```ruby
  if Settings.carrierwave.aws.endpoint.present?
    class CarrierWave::Storage::AWSFile
      def authenticated_url_with_endpoint(options = {})
        authenticated_url_without_endpoint(
          { endpoint: Settings.carrierwave.aws.endpoint }.merge(options)
        )
      end
      alias_method_chain :authenticated_url, :endpoint
    end
  end
```

But there is also problem with file uploads.

**Comment by Kukunin** [comment]
I've found the solution. I leave it here for gem users:

```ruby
    config.aws_credentials = {
      access_key_id:   "xxx",
      secret_access_key: "yyy",
      config: AWS.config({
        s3_endpoint: 's3-us-west-1.amazonaws.com'
      })
    }
```

**Comment by sorentwo** [comment]
Thanks for posting the fix. I'm sure it will be useful for others!

**Comment by simahawk** [comment]
I've stumbled upon this after 4yrs :sweat_smile: 
@Kukunin thanks for the pointer!
@sorentwo any chance to have an `S3_ENDPOINT` env var supported?
This would make easier to integrate even non-amazon S3 storages (like Exoscale in Switzerland) when deploying via containers.

**Comment by sorentwo** [comment]
@simahawk carrierwave-aws doesn't directly support any environment variables, they must be used manually within the configuration block. The aws-sdk may use environment variables automatically, but I don't have any control over that 🙂 

A PR to add this example to the README would be welcome!
