### ISSUE TITLE
Custom AWS Headers (primarily for file encryption server-side) with bucket policy

### ISSUE THREAD

**Issue by jancel** [sorentwo/carrierwave-aws#42]
I set up a bucket policy to require that files uploaded be server-side encrypted.  I got it all to work without the bucket policy, but here I'm needing to pass header and value.

``` config/initializers/carrierwave.rb
  CarrierWave.configure do |config|
   ...
    config.aws_attributes = {'x-amz-server-side​-encryption' => "AES256"}
  ...
  end
```

It doesn't seem to work and I'm not finding any documentation to the contrary.  Is there something I'm missing?

**Comment by jancel** [comment]
Found the option using AWS.config(...)

```
CarrierWave.configure do |config|
  ...
    config.aws_credentials = {
      access_key_id:     ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_KEY'),
      config: AWS.config(s3_server_side_encryption: :aes256)
    }
 ...
end
```

**Comment by sorentwo** [comment]
@jancel: Nice to see you figured it out. Thank you for posting the fix within the issue for others. There are far more possibilities with AWS than I know about or can cover in the README!

**Comment by rojotek** [comment]
FWIW I hit this as well. I'm put the settings in the aws_attributes in the uploader as follows:

```ruby
class AwesomeUploader < CarrierWave::Uploader::Base
  storage :aws

  def aws_attributes
    { server_side_encryption: 'aws:kms' }
  end
end
```
