### ISSUE TITLE
AWS and SSLv3 

### ISSUE THREAD

**Issue by pabuisson** [sorentwo/carrierwave-aws#43]
Hey,

My company and I recently received an email about Amazon WS disabling SSL v3 on May, 20th. They are encouraging users to move to TLS instead. Do you have any clue about the compatibility of `carrierwave-aws` with this, or do we need to do some work in order to get things ready for this transition ?

Thanks for your answer, I'll keep on digging about this but hope you'll be able to provide me some insight.

**Comment by sorentwo** [comment]
Ruby itself uses OpenSSL for secure connections. To my knowledge any modern install of OpenSSL will favor TLS, so you will be fine on the server side.

Connections to your S3 bucket from end users are most likely to be effected. How ever, if you target IE8 and above there won't be an issue.

**Comment by pabuisson** [comment]
Good to know, I'll follow what's being said on the AWS forums, but this makes me feel a little more confident about this. Thanks again !

**Comment by pabuisson** [comment]
Just gave it a try using the sslv3-disabled endpoint that Amazon has provided (see this thread for more information : https://forums.aws.amazon.com/thread.jspa?threadID=179904&tstart=0). I logged all the network activity using Wireshark and it seems that my application is using TLSv1.2, so we're all good. Using Ruby 2.2.0, carrierwave 0.10.0 and carrierwave-aws 0.5.0.

**Comment by sorentwo** [comment]
Thanks for the confirmation @pabuisson!
