### ISSUE TITLE
question about configs

### ISSUE THREAD

**Issue by anklos** [sorentwo/carrierwave-aws#44]
Hi there,

I configured my rails application as below:

```ruby
CarrierWave.configure do |config|
    config.storage    = :aws
    config.aws_bucket = 'a-unique-name'
    config.aws_acl    = :public_read
    config.asset_host = 'http://localhost:3000' # not sure what to put here
    # config.aws_authenticated_url_expiration = 60 * 60 * 24 * 365

    config.aws_credentials = {
      access_key_id:    'xxxx',
      secret_access_key: 'xxxx',
      region: 'Singapore'
    }
  end
```

And my uploader is:
```
def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def download_url(filename)
    url(response_content_disposition: %Q{attachment; filename="#{filename}"})
  end
```

So in this configuration, files are still uploaded to my local server, rather than S3. Is there anywhere I mis configured?

Another quick question, what is `config.assert_url` for?

Thanks a lot!

**Comment by anklos** [comment]
Just find some clue in the closed issues, `asset_url` seems means bucket url? 

I could find one endpoint in the `Static Website Hosting` section: vendorable-dev.s3-website-ap-southeast-1.amazonaws.com, not sure if it is the correct one. If not,  could you please point me out where in the below graph I could get my bucket url?

![image](https://cloud.githubusercontent.com/assets/530145/7666398/55e34798-fc27-11e4-8734-6a08a6a2ee77.png)

**Comment by anklos** [comment]
Just tried to set the `assert_url` to `https://s3-website-ap-southeast-1.amazonaws.com/vendorable-dev`, still uploaded the  file to my local server.

**Comment by ryanjohns** [comment]
I haven't tested this but I think you can just remove the `config.asset_host` option from your `CarrierWave.configure` block and change the value of your `region` parameter inside the `config.aws_credentials` hash to equal `'ap-southeast-1'`.

**Comment by anklos** [comment]
@ryanjohns thanks.

Tried that, it was still uploading files to my local server. is there any place I need to config/overwrite upload destination?

**Comment by ryanjohns** [comment]
Here's everything I have to make it work in my application. We're using us-east-1 but I think the only change needed for that is the `region: 'ap-southeast-1'` option that I mentioned previously.

Gemfile
```ruby
gem 'carrierwave'
gem 'carrierwave-aws'
```

config/initializers/carrierwave.rb
```ruby
if Rails.env.test?
  CarrierWave.configure do |config|
    config.storage           = :file
    config.enable_processing = false
  end
else
  CarrierWave.configure do |config|
    config.storage         = :aws
    config.aws_bucket      = "my-bucket-#{Rails.env}"
    config.aws_acl         = :private
    config.aws_attributes  = { :cache_control => 'max-age=315576000' }
    config.aws_credentials = {
      :access_key_id     => 'xxxx',
      :secret_access_key => 'xxxx',
    }
    config.aws_authenticated_url_expiration = 2.months
  end
end
```

app/uploaders/photo_uploader.rb
```ruby
class SignatureUploader < CarrierWave::Uploader::Base
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end
```

app/models/my_model_with_uploads.rb
```ruby
class MyModelWithUploads < ActionRecord::Base
  mount_uploader :photo_upload, PhotoUploader # photo_upload is the database column name
  validates_integrity_of :photo_upload
end
```

Hope this helps.

**Comment by anklos** [comment]
@ryanjohns Not sure if it is just a copy mistake, but in your `photo_uploader.rb`, it is `SignatureUploader`, not `PhotoUploader`. Could you please paste what is in your `PhotoUploader` class? Thanks!

**Comment by ryanjohns** [comment]
Yeah, that was just a typo and doesn't really affect the example. I updated the comment above to avoid confusion. That's the entire contents of my uploader, everything else is default. I'm not sure what else to tell you. Try checking the logs for any errors and make sure the bucket exists and is readable/writable by the credentials you are using. Maybe try getting it working with a USStandard bucket initially to eliminate the region as a potential source of problems.

**Comment by sorentwo** [comment]
It sounds like the configuration isn't really loading and carrier wave is defaulting to the file store. Another possibility is that the files are being cached locally and then never uploaded to aws, but you wouldn't see them in the usual `public` location in that case.

In any case the asset_host doesn't change where your files are hosted, so don't worry about it.

**Comment by sorentwo** [comment]
@anklos: Any progress here?

**Comment by anklos** [comment]
@sorentwo thanks mate, going to do some more debugging see where it is wrong. 

I can see the files uploaded to `public/uploads`, that's why I feel the carrierrwave-aws is not overwriting the old carrierwave configs.

**Comment by anklos** [comment]
figured why!!

need to remove `storage :file` from the `AttachmentUploader` class.

**Comment by sorentwo** [comment]
That would have done it. Glad you are all set!

**Comment by anklos** [comment]
thanks for all the help!
