### ISSUE TITLE
aws private url

### ISSUE THREAD

**Issue by anklos** [sorentwo/carrierwave-aws#46]
hi there,

just would like to double check, I get this kind of url by setting access to be private: `https://xxx.s3-ap-southeast-1.amazonaws.com/uploads/xxx/xxx/3/xxx.jpeg?AWSAccessKeyId=xxxxx&Expires=xxx&Signature=xxxxx`

Is it supposed/OK to expose `AWSAccessKeyId` in the url?

Config is like is:
```
config.aws_acl    = :private
config.aws_authenticated_url_expiration = 60
```

Thanks!

**Comment by anklos** [comment]
no worries, just find the documentation about the signed url format. All good.

**Comment by joseronierison** [comment]
Where is the documentation? @anklos 

Regards

**Comment by anklos** [comment]
@johanneswuerbach http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html

**Comment by johanneswuerbach** [comment]
Looks like you wanted to ping somebody different :-) maybe @joseronierison

**Comment by anklos** [comment]
sorry @johanneswuerbach no idea why your name is in the auto complete list
