### ISSUE TITLE
aws_attributes not working as expected

### ISSUE THREAD

**Issue by leandromoreira** [sorentwo/carrierwave-aws#51]
I first searched for a solution which pointed me to this https://github.com/sorentwo/carrierwave-aws/issues/12 and then I added that to my initializer:

```ruby
config.aws_attributes = {
  'cache_control' => 'public,max-age=315576000',
  'expires' => 1.year.from_now.httpdate
}
```

But my uploaded images don't have these attributes. I'm using:
```Gemfile
    carrierwave-aws (0.3.2)
      aws-sdk (>= 1.8.0)
```

**Comment by sorentwo** [comment]
The `Cache-Control` header must be written exactly, it isn't modified like typical rack headers.

```ruby
config.aws_attributes = { 'Cache-Control' => 'max-age=315576000' }
```

Separately, you should upgrade to 0.5.0, there are some bug fixes and no API breakage.

**Comment by ryanjohns** [comment]
I just want to add that using symbols instead of strings for your config options will also work.

```ruby
config.aws_attributes = { 'Cache-Control' => 'max-age=315576000' }
```
is equivalent to
```ruby
config.aws_attributes = { :cache_control => 'max-age=315576000' }
```

**Comment by leandromoreira** [comment]
Thanks @sorentwo and @ryanjohns
