### ISSUE TITLE
New gem version release

### ISSUE THREAD

**Issue by galetahub** [sorentwo/carrierwave-aws#52]
Hi Parker,
Please, release new gem version to rubygems.org.
We need to use new aws-sdk 2.x 
Thanks

**Comment by sorentwo** [comment]
@galetahub: I'm getting there. Object data access changed in aws-sdk-2, so I'm currently working through the `file#read` behavior. Once that is working I'll release the next version.

**Comment by sorentwo** [comment]
@galetahub: Please try using `1.0.0-rc.1` to evaluate using AWS-SDK v2.
