### ISSUE TITLE
IAM Profile Credentials

### ISSUE THREAD

**Issue by jonmchan** [sorentwo/carrierwave-aws#53]
Does carrierwave-aws support getting credentials from the iam_profile like fog-aws supports?

https://github.com/fog/fog-aws/blob/916351a3532e80a0318e766ec12bb87fa2348350/lib/fog/aws/credential_fetcher.rb

**Comment by sorentwo** [comment]
IAM access works directly through the `aws-sdk` gem, you don't need to do anything within `carrierwave-aws` at all. There's a post from a few years ago about this:

http://ruby.awsblog.com/post/TxP3XGEX8F3SHX/IAM-Roles-for-Amazon-EC2-Instances-Credential-Management-Part-4

**Comment by jonmchan** [comment]
Sweet - it does work. Thanks. For reference, all you have to do is leave out the access_key_id and the secret_key and it will work.
