### ISSUE TITLE
Unexpected behaviour setting field to nil

### ISSUE THREAD

**Issue by trebor8x** [sorentwo/carrierwave-aws#54]
Hi there,

with an  uploader mounted on a field `urls_file`, setting this field to `nil` has confusing behavior.
`model.urls_file = nil` sets a weird path:

```
@file=#<CarrierWave::Storage::AWSFile:0x0000000be93210
...
 @path="uploads/model/urls_file/558c1d33af53dbc48000002f/_old_"
...
```

Moreover a `model.urls_file.present?` now returns `true`.
This differs from other carrierwave storages (like filestorage).

**Comment by sorentwo** [comment]
Can you please share the version of carrierwave and carrierwave-aws that you're using?

**Comment by trebor8x** [comment]
Sure thing:
```
carrierwave (0.10.0)
carrierwave-aws (0.5.0)
carrierwave-mongoid (0.7.1)
carrierwave-sequel (0.1.0)
```

**Comment by sorentwo** [comment]
@trebor8x: I can definitely recreate the issue, but I haven't found a solution yet. It hasn't been forgotten!

**Comment by ngw** [comment]
Same problem here

        it 'should contain a file' do
          picture = dog.pictures.last
          picture.photo_file = nil
          expect(picture).not_to be_valid
        end

Also using remove! doesn't help. Spec commented out ATM...
