### ISSUE TITLE
unexpected value at params["Content-Disposition"]

### ISSUE THREAD

**Issue by theB264** [sorentwo/carrierwave-aws#57]
Since trying to update to `carrierwave-aws 0.6.0` from `0.5.0` these errors keep preventing anything from being uploaded:

`unexpected value at params["Content-Disposition"]`
`ArgumentError (unexpected value at params["Content-Disposition"])`

``` ruby
    aws-sdk (2.0.48)
      aws-sdk-resources (= 2.0.48)
    aws-sdk-core (2.0.48)
      builder (~> 3.0)
      jmespath (~> 1.0)
      multi_json (~> 1.0)
    aws-sdk-resources (2.0.48)
      aws-sdk-core (= 2.0.48)
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave-aws (0.6.0)
      aws-sdk (~> 2.0.47)
      carrierwave (~> 0.7)
```

**Comment by sorentwo** [comment]
Can you please share your configuration block and any related code from your uploader?

**Comment by theB264** [comment]
``` ruby
  CarrierWave.configure do |config|
    config.storage    = :aws
    config.aws_bucket = ENV['BUCKET_NAME']
    config.aws_acl    = :'authenticated-read'
    config.asset_host = 's3-country-region-1.amazonaws.com/dir_name'
    config.aws_authenticated_url_expiration = 60 * 60
    config.aws_attributes = {'Content-Disposition' => 'Attachment'}
    config.aws_credentials = {
      access_key_id:     ENV['ACCESS_KEY_ID'],
      secret_access_key: ENV['SECRET_ACCESS_KEY'],
      region:            ENV['REGION']
    }
  end
```

``` ruby
  include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :aws
```

**Comment by sorentwo** [comment]
The format for accepted attributes changed between `aws-sdk-1` and `aws-sdk-2`. Only lower snake cased values are allowed now. Try using `content_disposition: 'Attachment'` instead and let me know how it goes.

**Comment by theB264** [comment]
I'm still getting `ArgumentError (unexpected value at params["Content-Disposition"])` on `Widget.create` where Widget would be a model.  The error is from this line https://github.com/aws/aws-sdk-ruby/blob/v2.0.48/aws-sdk-core/lib/seahorse/client/param_validator.rb#L50

**Comment by sorentwo** [comment]
Internally it is using the `object#put` method, which lists the exact options that it accepts. Here is a complete list in the aws docs:

http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#put-instance_method

**Comment by theB264** [comment]
I'm not sure.  I've tried every combination of nothing, `content_disposition`, `ContentDisposition`, `Content-Disposition` etc and this still appears regardless.  It's coming from
``` ruby
Parameters: {"utf8"=>"✓", "authenticity_token"=>"a_big_string", "widget"=>{"attachment"=>#<ActionDispatch::Http::UploadedFile:0x00000004928e00 @tempfile=#<Tempfile:/tmp/RackMultipart20150630-26966-vngmu5.png>, @original_filename="copyleft.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"widget[attachment]\"; filename=\"copyleft.png\"\r\nContent-Type: image/png\r\n">}, "commit"=>"Next"}
``` and I'm not sure how it's getting there

**Comment by sorentwo** [comment]
Is the upload being assigned directly, i.e. `model.image = params[:attachment]`? If so you can try pulling out just the tempfile or clearing the headers.

**Comment by theB264** [comment]
I aborted and went a separate direction because it doesn't seem to work.

**Comment by sorentwo** [comment]
@theB264: I hope your new direction works out. If this is a bug that effects other people I'd like to get it sorted out eventually.

**Comment by theB264** [comment]
I never could figure out where it was coming from.  I wish I could help; I had to move on and do things a different way. :-)

**Comment by Reyitgex** [comment]
I just bumped into this issue today and fixed it by using response_content_disposition instead of content_disposition
