### ISSUE TITLE
Should upgrading to aws-sdk 2.0 have been a major version change?

### ISSUE THREAD

**Issue by mockdeep** [sorentwo/carrierwave-aws#58]
When we upgraded our gems recently our site was broken due to a major breaking upgrade to `aws-sdk` via the dependency from `carrierwave-aws`. It seems to me that a change such as this should also result in a major version bump to `carrierwave-aws`.

**Comment by sorentwo** [comment]
I had the same thought earlier today https://twitter.com/sorentwo/status/615938839543033856

My original thinking was that because `carrierwave-aws` was pre-1.0 a set of changes like this wouldn't be a problem. That thinking has proven incorrect. There are a lot of breaking changes within `aws-sdk-2` and apparently a lot more users of the gem than I had guessed. I'm working on an alternate version strategy currently.

**Comment by mockdeep** [comment]
Yeah, I'm of the mind that even pre-1.0 should adhere to semantic versioning, though I guess it would be good to have a way to indicate that something isn't stable yet.

**Comment by sorentwo** [comment]
I'm strongly considering bumping the current release to `1.0.0-pre` and releasing a `0.7.0` with a reversion to `aws-sdk-1`. That should prevent some of the issues you (and other's) are running into, while giving an upgrade path as well.

Honestly the upgrade has been a huge pain to me with no actual benefits. The maximum expiration time is now only 1 week, signed urls are insanely long, and it is pickier about passed configuration values. I'm sure it has improved things for the aws-sdk gem internally, but it has been a hassle.

**Comment by mockdeep** [comment]
> I'm strongly considering bumping the current release to 1.0.0-pre and releasing a 0.7.0 with a reversion to aws-sdk-1. That should prevent some of the issues you (and other's) are running into, while giving an upgrade path as well.

I am in favor of this idea. 

> Honestly the upgrade has been a huge pain to me with no actual benefits. The maximum expiration time is now only 1 week, signed urls are insanely long, and it is pickier about passed configuration values. I'm sure it has improved things for the aws-sdk gem internally, but it has been a hassle.

I remember running into something similar with `fog` a while back before switching to this. I bet things like that help to reduce the number of support requests they get on their end.

**Comment by sorentwo** [comment]
New releases are out. `0.7.0` is identical to `0.5.0`, which will trump any eagerly installed `0.6.0` versions. The upgrade to AWS-SDK v2 is now wrapped up in `1.0.0-rc.1`. Thanks for the collaboration!

**Comment by mockdeep** [comment]
Sounds great. Thanks!
