### ISSUE TITLE
Cloudfront not working

### ISSUE THREAD

**Issue by musixite** [sorentwo/carrierwave-aws#66]
Hi there,

Thanks for your gem, it's working fine!

However, after setting up
  config.asset_host = 'https://[myid].cloudfront.net'

+ restart server.

The images are still served from the S3 bucket.
Is there another setting I forgot to do?

Thanks!
- Vincent

**Comment by sorentwo** [comment]
@musixite Which version are you using? There are large differences between the `0.X` and `1.X` releases.

**Comment by musixite** [comment]
I'm using the following:
# Use carrierwave for file uploads
gem 'carrierwave', '~> 0.10.0'

# Use Minimagick for image tools
gem 'mini_magick', '~> 4.2.10'

# Use carrierwave-aws for amazon S3 storage
gem 'carrierwave-aws', '~> 0.7.1'

**Comment by musixite** [comment]
So I tried install carriewave v1.0 and it now works.

Thanks for pointing me out to the right direction,
- Vincent

**Comment by sorentwo** [comment]
Glad an upgrade worked out!
