### ISSUE TITLE
uninitialized constant Aws::CF

### ISSUE THREAD

**Issue by casiodk** [sorentwo/carrierwave-aws#70]
Hi, I´m getting this error when running my tests.

    Failure/Error: get :shared, { format: :json, id: image.id, token: image.token }
         ActionView::Template::Error:
           uninitialized constant Aws::CF
         # ./config/initializers/carrierwave.rb:29:in `block (2 levels) in <top (required)>'
         #  /Users/nicolaiseerup/.rvm/gems/ruby-2.2.3/bundler/gems/carrierwave-aws-    900b3a2b2907/lib/carrierwave/storage/aws_file.rb:64:in `call'
          # /Users/nicolaiseerup/.rvm/gems/ruby-2.2.3/bundler/gems/carrierwave-aws-900b3a2b2907/lib/carrierwave/storage/aws_file.rb:64:in `signed_url'
         # /Users/nicolaiseerup/.rvm/gems/ruby-2.2.3/bundler/gems/carrierwave-aws-900b3a2b2907/lib/carrierwave/storage/aws_file.rb:81:in `url'

This is my config file:

    CarrierWave.configure do |config|
      config.storage            = Rails.env.test? ? :file : :aws
      # config.storage            = :aws
      config.aws_bucket         = "#{ ENV['S3_DIRECTORY'] }#{ Rails.env }"
      config.aws_acl            = 'private'
      config.enable_processing  = false if Rails.env.test?
      # Optionally define an asset host for configurations that are fronted by a
      # content host, such as CloudFront.
      config.asset_host = ENV['CDN_ASSET_HOST']
      # The maximum period for authenticated_urls is only 7 days.
      config.aws_authenticated_url_expiration = ENV['ASSETS_EXP_TIME'].to_i + 60
      # Set custom options such as cache control to leverage browser caching
      config.aws_attributes = {
        expires: 1.week.from_now.httpdate,
        cache_control: 'max-age=604800'
      }
      config.aws_credentials = {
        access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        region:            ENV['AWS_REGION']
      }

    # Optional: Signing of download urls, e.g. for serving private
    # content through CloudFront.
    config.aws_signer = -> (unsigned_url, options) { Aws::CF::Signer.sign_url unsigned_url, options }
end

**Comment by tscholz** [comment]
Hi,

the aws_signer shouldn't be called in your test environment as you have set the storage to `:file`. Maybe you have the storage overridden within your uploader?

Btw, in order to use the Aws::CF::Signer you will have to add the [aws_cf_signer](https://github.com/dylanvaughn/aws_cf_signer) gem to your Gemfile.

**Comment by casiodk** [comment]
Hi I tried to use this gem
https://github.com/leonelgalan/cloudfront-signer

Would that work or does it have to be the other one?

**Comment by casiodk** [comment]
I think its almost working

but i get an access denied error when trying to serve the image through cloudfront
http://d22jn7byz1lanq.cloudfront.net/uploads/image/image/377/filename.jpeg?Expires=1442954873&Signature=c3G~mmkYFAWUQeBr3pvRlfmcrB34j4rm7cHOKTXUNvESPqgN3iKoN2EFF5hy5UFZ48NvCSe2-K~MEb1Y1zRPWv~BXLTbGNUFEfl18gozseg8LWSFHKhBi6zMg0WA92BRCDU0rNiRegYm82A~RpRMcFTuzDIP5sr98D82tVc6ndUfJCXEc~qMAUz94viFfp23VotYnXz0VrQWVezd-JmolwtWdKmDgL9axe1nYgPbVbNmiyFAd4fa6Oo~HDwrydi8ZSx5~rUnnryFcu0oCjhEkI0coLqW7hUgoNf9JerFHcHDDEm-hIzeItvmR4u0yniwRlO6Smu2IfgK-MqZbi2E1w__&Key-Pair-Id=APKAJTOZWWBIOH5TSSTA

**Comment by casiodk** [comment]
I changed the sihning gem which resulted in uninitialized constant Aws::CF
