### ISSUE TITLE
S3 Download Url with attachment attribute (mp3 opens file instead of downloading)

### ISSUE THREAD

**Issue by musixite** [sorentwo/carrierwave-aws#72]
Hi there,

I've been scratching my head for a while to be able to bring a download link (for a mp3 file) to work.

I tried the redirect method but it opens the file in the browser instead of downloading it.
I also tried with send data but it copies the file first which makes it useless (it takes too much processing time).

What I want to achieve is to stream the S3 file so that the user can download it directly.

I tried to add the attribute "content_disposition: "Attachment" in my carrier wave initializer without success.

I suspect this could be achieved with the S3 object

```
def download_url
  S3 = AWS::S3.new.buckets[ 'bucket_name' ] # This can be done elsewhere as well.

  S3.objects[ self.path ].url_for( :read,
    expires_in: 60.minutes, 
    use_ssl:    true, 
    response_content_disposition: "attachment; filename='#{attachment_file_name}'" ).to_s
end
```

But I don't know how to get access to the S3 object with carrierwave-aws (and I don't even know if the above code would work).

I'm sure this is pretty straight-forward to do but I'm stuck.

Any ideas?
Thanks!
- Vincent

**Comment by sorentwo** [comment]
You don't get direct access to the S3 object, but you can add custom attributes to it with `aws_read_options`. This is something you can do for a particular uploader:

```ruby
  configure do |config|
    config.aws_read_options = {
      content_disposition: 'attachment; filename='hardcoded_filename.mp3'
    }
  end
```

That will help with reading, but that still requires pulling the data down. Instead, you may want to set the `content_disposition` when writing the content. In that case, use:

```ruby
  configure do |config|
    config.aws_write_options = {
      content_disposition: 'attachment'
    }
  end
```

Hope that helps!

**Comment by musixite** [comment]
I tried to do what you mentioned but this doesn't change the fact that it copies the file first which takes 10-15sec to process. First option is not possible since I need to retrieve the filename from the database.

Still looking!

Thanks for your help,
- Vincent

**Comment by sorentwo** [comment]
If you write the header along with the content you can just use the generated url rather than copying the file locally. If you have to use `read` there is no way around downloading the file to the local server.

**Comment by pake007** [comment]
hi @musixite Your code is working for aws-sdk-v1, since carrierwave-aws relies on aws-sdk v2, it is not working anymore. However, in v2, aws-sdk has a method :presigned_url defined in Aws::S3::Object, you can use this method to construct the direct download url for a s3 object:

```
s3 = Aws::S3::Resource.new
# YOUR-OBJECT-KEY should be the relative path of the object like 'uploads/user/logo/123/pic.png'
obj = s3.bucket('YOUR-BUCKET-NAME').object('YOUR-OBJECT-KEY')
url = obj.presined_url(:get, expires_in: 3600, response_content_disposition: "attachment; filename='FILENAME'")
```
