### ISSUE TITLE
Need ability to `move_to`

### ISSUE THREAD

**Issue by brentdodell** [sorentwo/carrierwave-aws#73]

**Comment by sorentwo** [comment]
Is there an interface presented by carrierwave that you are expecting to provide `move_to`? Also, I saw that you forked the repo. Are you working on a PR for this?

**Comment by brentdodell** [comment]
> Is there an interface presented by carrierwave that you are expecting to provide move_to?

[I believe so](https://github.com/carrierwaveuploader/carrierwave/blob/1e4e7b0bf20fee70d8ac3815d0921144f39e14cf/lib/carrierwave/sanitized_file.rb#L174-L200)

> Also, I saw that you forked the repo. Are you working on a PR for this?

I'm not used to developers responding so quickly! Thank you for doing so. I am attempting to put together a PR, but I'm fresh out of college and haven't been programming long. Also, I've only been using Ruby for a year, so it may end up not being useable.

I was going to try to use `copy_to`, and then `delete`.

**Comment by olivierlacan** [comment]
@brentdodell To be fair this `move_to` method is used on SanitizedFile for local file storage purposes. CarrierWave::Storage::Fog doesn't currently have a `move_to` method. 

I'd also find this method useful but @sorentwo do you think we should add methods with no existing equivalents in CarrierWave?

**Comment by sorentwo** [comment]
If there is a use case for this, that can't be achieved simply with the aws-sdk itself, then I'm in favor. Otherwise I don't want to start adding convenience / delegate methods that don't have any equivalent in CarrierWave.

Either way, this issue is rather stale and lacks a use case (or any context), so I'm closing it for now.
