### ISSUE TITLE
After an Ubuntu update miniMagick::Error ImageMagick/GraphicsMagick

### ISSUE THREAD

**Issue by MicFin** [sorentwo/carrierwave-aws#75]
Please see the following error

http://stackoverflow.com/questions/34861390/after-ubuntu-update-imagemagick-graphicsmagick-is-not-installed-error

**Comment by sorentwo** [comment]
The linked question has been removed, so I can't read the question at all. Regardless, `carrierwave-aws` only handles uploading, it doesn't contain any processing logic at all. All of the {Mini,R}Magic code is in carrierwave/carrierwave itself.

**Comment by MicFin** [comment]
Thank you for closing.
