### ISSUE TITLE
undefined method `aws_bucket=' for CarrierWave::Uploader::Base:Class

### ISSUE THREAD

**Issue by DonKoko** [sorentwo/carrierwave-aws#76]
Hey,

I integrated the carrierwave-aws to our rails app and I its working on local, but I am getting weird errors when trying to deploy to AWS using EB CLI. 
After trying to run `rake db:migrate`, rake is aborted with the following error:
`NoMethodError: undefined method 'aws_bucket=' for CarrierWave::Uploader::Base:Class`

This is how my `carrierwave.rb` file looks like: 

`CarrierWave.configure do |config|`
 `config.storage    = 'aws'`
 `config.aws_bucket = ENV.fetch('S3_BUCKET_NAME')`
 `config.aws_acl    = 'private'`

  # The maximum period for authenticated_urls is only 7 days.
  `config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7`

  # Set custom options such as cache control to leverage browser caching
 ` config.aws_attributes = {`
      `    expires: 1.week.from_now.httpdate,`
     `     cache_control: 'max-age=315576000'`
 ` }`

`  config.aws_credentials = {`
  `    access_key_id:     ENV['AWS_ACCESS_KEY_ID'],`
  `    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],`
   `   region:            ENV['AWS_REGION'] # Required`
`  }`
`end`

Inside my gemfile I have tried to do it with both:
`  gem 'carrierwave'`
`  gem 'carrierwave-aws', '~> 1.0.0'`
as well as only with the  `gem 'carrierwave-aws', '~> 1.0.0'` and error persists.

Any ideas on what might be causing this. I thought it might be some dependency issue but couldn't find anything.

**Comment by sorentwo** [comment]
It looks like the `carrierwave` config initializer is getting called before `carrierwave-aws` is loaded. The config attributes like `aws_bucket` are only available after `carrierwave-aws` has loaded. You can try requiring `carrierwave-aws` explicitly before the config block is run.

**Comment by DonKoko** [comment]
That solved the issue. Thanks for the help.
Uploader doesn't work tho. We switched to this gem to avoid an issue, but the issue still persists :
`Aws::S3::Errors::SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided`

**Comment by sorentwo** [comment]
It sounds like that is definitely a problem with your application or aws configuration itself. The uploader definitely works, and for many people.

**Comment by DonKoko** [comment]
Problem is solved. Gem works great!. Thanks for the help.
