### ISSUE TITLE
image_tag issues

### ISSUE THREAD

**Issue by jasper502** [sorentwo/carrierwave-aws#77]
I am only starting here because the issue cropped up after I switched from fog to carrierwave-aws.  My image tags are rendering like this:

    <%= image_tag(current_user.avatar.thumb.url, class: "img-circle") %>    
    <img class="img-circle" src="https://xxxx.cloudfront.net/images/xxx.cloudfront.net/user/9/avatar_thumb.png" alt="Avatar thumb">

but `current_user.avatar.thumb.url` outputs `https://xxxx.cloudfront.net/user/9/avatar_thumb.png`.

**Comment by sorentwo** [comment]
It looks like image tag is doubling up the asset host. The value of avatar.thumb.url is correct and all that is controlled by carrierwave-aws, so it seems like a configuration issue.

**Comment by jasper502** [comment]
where is the `/images/` coming from though??

**Comment by sorentwo** [comment]
That would be coming from the image tag helper. Just like the font or stylesheet variants, it builds on asset_tag to insert a more specific path.

If you remove the cdn from your asset path does the URL look correct?

**Comment by jasper502** [comment]
D'oh!

    config.asset_host = "https://xxxx.cloudfront.net"

not:

    config.asset_host = "xxxx.cloudfront.net"
