### ISSUE TITLE
copy_to is not using aws_acl settings

### ISSUE THREAD

**Issue by olivierlacan** [sorentwo/carrierwave-aws#81]
This results in world-inaccessible files being created on copy. I've verified this on an S3 bucket.

Context:
- uploader `filename` depends on `model_identifier`
- model attribute that impacts `model_identifier` is changed
- filename is updated, we have a rename method that copies the file to the new expected location
- the original file's acl is `public-read`, the copied file's acl isn't

[`CarrierWave::Storage::AWSFile#copy_to`](https://github.com/sorentwo/carrierwave-aws/blob/bc69db85bd77681304e2be7b50e6db109eac5588/lib/carrierwave/storage/aws_file.rb#L45-L47) doesn't pass acl options to [aws-sdk's `copy_from`](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#copy_from-instance_method) (which accepts them). 

See the corresponding implementation in [`CarrierWave::Storage::Fog#copy_to`](https://github.com/carrierwaveuploader/carrierwave/blob/1778cd4577fdcbf4a383802b31dc7c1e4481e942/lib/carrierwave/storage/fog.rb#L409-L411)

It [defers to an `acl_header` method](https://github.com/carrierwaveuploader/carrierwave/blob/1778cd4577fdcbf4a383802b31dc7c1e4481e942/lib/carrierwave/storage/fog.rb#L454-L456) that checks the `fog_public` configuration option, but in carrierwave-aws's case it seems like the `aws_acl` configuration option would be more appropriate. 

If this sounds like a bug to you too, I'll submit a pull request to address this issue.

This issue may be tangentially related to #73 since it would suffer from the same isssue.

**Comment by sorentwo** [comment]
Thanks for the excellent write up. It definitely sounds like a bug to me, and I'd welcome a pull request.

**Comment by olivierlacan** [comment]
You're welcome. I'm currently struggling with figuring out how to check for an S3Object's shorthand ACL (`public-read`) from aws-sdk-ruby. The [documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/ObjectAcl.html) is not really helping so if you know, that might help me out.

**Comment by olivierlacan** [comment]
Calling @awood45 to the rescue because I'm lazy and this is relevant to his interests anyway.

**Comment by sorentwo** [comment]
@olivierlacan Sorry to say that I don't know. My knowledge of the aws-sdk-ruby gem is not extensive.

**Comment by olivierlacan** [comment]
All right. The only thing I can find to compare access is so deeply nested it seems utterly absurd but here goes: 

```ruby
original.file.file.acl.grants
=> [#<struct Aws::S3::Types::Grant
  grantee=
   #<struct Aws::S3::Types::Grantee
    display_name="vendor+aws",
    email_address=nil,
    id="45836e7b6274ab9b2adab5c56dc23bc4eca041d5cb8c03506f2a2693c96abc59",
    type="CanonicalUser",
    uri=nil>,
  permission="FULL_CONTROL">,
 #<struct Aws::S3::Types::Grant
  grantee=
   #<struct Aws::S3::Types::Grantee
    display_name=nil,
    email_address=nil,
    id=nil,
    type="Group",
    uri="http://acs.amazonaws.com/groups/global/AllUsers">,
  permission="READ">]
```

The `copy` only has one grant (the owner) and we could check for the `AllUsers` URI. It seems extremely brittle to me but until I can find something better I'll use that.

**Comment by awood45** [comment]
@olivierlacan To the best of my knowledge, canned ACLs are write-only. `public-read`, for example, is shorthand for:

```ruby
#<struct Aws::S3::Types::Grant
    grantee=#<struct Aws::S3::Types::Grantee display_name=nil, email_address=nil, id=nil, type="Group", uri="http://acs.amazonaws.com/groups/global/AllUsers">,
    permission="READ">
```

Are you trying to support copying the ACL verbatim in all cases, or just to identify canned ACLs?

**Comment by olivierlacan** [comment]
@awood45 I ended up just comparing the list of grants. Does that seem like a good usage? https://github.com/sorentwo/carrierwave-aws/blob/eda2dfbc99ff61ef5b9e9fab6bf754303edd3fb9/spec/features/copying_files_spec.rb#L22-L26

**Comment by awood45** [comment]
I mean, the unit test looks correct (to validate that the objects have the same ACL grants). Let me dive in around this a bit more to understand how you got there.

**Comment by awood45** [comment]
After a quick catch-up online, it looks like the way you're ensuring the canned ACL is applied will work, and that your test does look for that. If you're trying to support the copying of more complex ACLs (think "enterprise user with multiple read/write ACLs for access control and security reasons"), this won't be able to reflect that and you'd want a strategy that uses `#get_object_acl` and `#put_object_acl` to put exactly the ACLs you want. This would work for canned ACLs too since they're just shorthand for the associated ACLs (though if you're supporting cross-user copies, you might have to add more cases to check for).

**Comment by olivierlacan** [comment]
Thanks a lot for the double-check @awood45. Closing this since fixed via #82.

**Comment by sorentwo** [comment]
Thanks @awood45. This has been educational. In my opinion the canned ACL is fine, especially since I don't have an enterprise use case that warrants more complex behavior.

**Comment by awood45** [comment]
100% understood, just wanted to answer thoroughly just in case. Glad this got solved!
