### ISSUE TITLE
AWS credentials from instance profile.

### ISSUE THREAD

**Issue by Startouf** [sorentwo/carrierwave-aws#85]
My Rails application is running on an EC2 Instance. I am relying on the instance profile / IAM Roles to get credentials for all my aws related operations (using the `aws` gem, this is done automatically and I don't need to worry about credentials).

Is there a way to also authenticate using instance profile with carrierwave-aws ? What should I write in the configuration ?

**Comment by sorentwo** [comment]
There was an issue about this a little while back: https://github.com/sorentwo/carrierwave-aws/issues/53. The short answer is, it is handled by the aws gem and you don't need to do anything, it will just work.
