### ISSUE TITLE
Aws::S3::Errors::NotFound completely blocking the model

### ISSUE THREAD

**Issue by Startouf** [sorentwo/carrierwave-aws#86]
I have an uploader that had uploaded some files on the S3 Cloud. For some reason, the files were remotely destroyed, so the user is left with a broken uploader.

Every attempt to save the model or remove the image with `remove_mounted_as` from the console throws a 

> Aws::S3::Errors::NotFound

I have also tried `user.mounted_as = nil; user.save`, but still the same error.

**Comment by sorentwo** [comment]
This may be related to a file existence bug that I'm aware of, but it could also be something strange in CarrierWave's tangled web of AR callbacks. I suggest working around CarrierWave's callbacks by overwriting the column directly with `update_column`, or `update_columns`.

**Comment by Startouf** [comment]
So mongoid in this case.

**Comment by sorentwo** [comment]
Whatever it is, bypass callbacks and modify the data directly.

**Comment by Startouf** [comment]
Alright, the problem is worse. It seems that removing images with `:remove!` or even updated with blank params for the avatar cause that crash (permanently !). I had added some extra code in my model because I had problems with CloudFront cache, and I believe this might be the source of the problem (see the last line `url`, from this [SO](http://stackoverflow.com/a/13327123/2832282)). 

My Uploader
```
require 'carrierwave/processing/mini_magick'

class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  process resize_to_fill: [200, 200]

  version :smaller do
    process resize_to_fill: [100, 100]
  end

  version :thumb do
    process resize_to_fill: [50, 50]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end
  def filename
    "avatar.#{file.extension}" if original_filename
  end

  def url(options={})
    super.split("?v=")[0]+"?v=#{model.updated_at.to_time.to_i}" rescue super
  end

end

```

Reproducible steps
```
u = User.me
u.avatar? # => true
u.avatar_url => "https://xxx.net/uploads/user/avatar/575722626ba9ba0b9d4e98d8/avatar.jpg?v=1467542978"
u.save # => true
# Now we make it crash
u.avatar.remove! # => [:remove_versions!]
u.avatar? # => true # wtf already
u.avatar_url # => [same as above]
u.save # => Aws::S3::Errors::NotFound:
```

Trace
```
from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/request.rb:70:in `send_request'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/request.rb:24:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/operations.rb:41:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/operations.rb:61:in `call'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/resource.rb:147:in `load'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/resource.rb:120:in `data'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.11/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/carrierwave-aws-1.0.1/lib/carrierwave/storage/aws_file.rb:7:in `size'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/proxy.rb:57:in `size'
        from /var/www/mysite/shared/bundle/ruby/2.3.0/gems/file_validators-2.1.0/lib/file_validators/validators/file_size_validator.rb:21:in `block in validate_each'
```

**Comment by Startouf** [comment]
If I delete the avatar, the filename of the URL is replaced with `_old_` and it still crashes

**Comment by Startouf** [comment]
I'm not sure I understand how to override properly the fields. When I do `user.attributes`, it only shows the avatar filename and not the full path of the uploader.
Also, how do I do it for every version ?

**Comment by sorentwo** [comment]
@Startouf I'm sorry you're having so much ongoing trouble. It has been a while, so I hope you've been able to work through this issue a little. Lately I'm swamped and haven't had time to dig into the underlying issues with deletion.

I've spent *many* hours in the past trying to track down where things go wrong, but with the way CarrierWave is structured out of class eval and callbacks it is *very* difficult to break down.

**Comment by Startouf** [comment]
I still have problems.
I realized however the problems were linked to the gem file_validator. Apparently callbacks that check file size/content are still fired even when there is no file.
Even removing the validations in the model wasn't enough, I had to permenently remove the gem

Even removing the validations in the model wasn't enough, I had to permenently remove the gem
 
How can I validate my file uploads with carrierwave-aws without causing crashes like this ?

**Comment by sorentwo** [comment]
This has lingered open for a while. You never received any feedback from the maintainer of file_validator, so I'm sure you found an alternate route. I'm closing this at this point.

**Comment by Startouf** [comment]
The alternate route (which isn't a solution at all) was to remove all file validations from my code. RIght now they are still deactivated and I'm still looking for a solution.

**Comment by cmalpeli** [comment]
@Startouf did you ever find a solution for this.  Encountering something similar.  If a user tries to delete an image, it triggers a `Aws::S3::Errors::NotFound` error :(

**Comment by courtsimas** [comment]
Strangely, I still have this issue.
