### ISSUE TITLE
How to test methods of  CarrierWave::Storage::AWS::File class?

### ISSUE THREAD

**Issue by luizs81** [sorentwo/carrierwave-aws#87]
I'm trying write tests that asserts the value of the `file.url` method. 
However, during the tests, `file` is a instance of `CarrierWave::SanitizedFile` instead of  `CarrierWave::Storage::AWS::File`, and therefore doesn't have the `url` method.

Any clue of how to achieve this?

Thanks a lot

**Comment by sorentwo** [comment]
It sounds like you're getting a file instance that hasn't been persisted yet. CarrierWave is in control until the `store!` or `retrieve!` methods are called, at which point the `SanitizedFile` object is wrapped in `AWSFile`. If you take a look at [storing_files_spec.rb](https://github.com/sorentwo/carrierwave-aws/blob/master/spec/features/storing_files_spec.rb#L56) you can see that the file is stored and then retrieved to verify the url.

Hope that helps.

**Comment by sorentwo** [comment]
If anything new comes up please let me know. Closing this for now.
