### ISSUE TITLE
NameError Exception: uninitialized constant Aws::CF

### ISSUE THREAD

**Issue by joshkinabrew** [sorentwo/carrierwave-aws#88]
I'm getting this error when trying to use the aws_signer option according to the documentation in the README.

Here's my carrierwave config file:

```ruby
CarrierWave.configure do |config|
  config.aws_credentials = {
    access_key_id:      'my-key',
    secret_access_key:  'my-secret',
    region:             'us-east-1'
  }

  config.asset_host = 'my-cloudfront-endpoint'

  config.aws_bucket = 'my-bucket'

  config.aws_signer = -> (unsigned_url, options) { Aws::CF::Signer.sign_url(unsigned_url, options) }
end
```

I tried switching to use

```ruby
config.aws_signer = -> (unsigned_url, options) { Aws::CloudFront::UrlSigner.new.sign_url(unsigned_url, options) }
```
as I was troubleshooting but it gave me an error about a missing ```key_pair_id``` (documentation [here](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFront/UrlSigner.html#signed_url-instance_method) )

Any pointers are appreciated 😄

**Comment by sorentwo** [comment]
As noted in #70, you'll need to use the [aws_cf_signer](https://github.com/dylanvaughn/aws_cf_signer) gem. This has come up enough that I think I need to  make a note in the README.

**Comment by joshkinabrew** [comment]
Yep that would be a good idea. Thanks!

**Comment by sorentwo** [comment]
Documentation has been updated!
