### ISSUE TITLE
Private ACL and NOT signing URLs

### ISSUE THREAD

**Issue by jasper502** [sorentwo/carrierwave-aws#90]
I am using carrierwave-aws and Cloudfront CDN to serve private files.  I am wanting to use Signed Cookies ONLY.  If a user signs out the cookies gets cleared and Cloudfront will stop serving the files.  The issue is that if the URLS are signed the files keep getting served as that is the default behaviour on Cloudfront.

So if I try and disable 'config.aws_signer' on my `carrierwave.rb` file two weird things happen: I loose my `config.asset_host` and CW tries to serve from my CDN hostname (https://mybucketname.s3-us-west-2.amazonaws.com) vs the `config.asset_host` setting (mybucketname.mydomain.tld) etc.  and the URLs have a bunch of `X-Amz` tokens.

I suspect the issue is that because I have `config.aws_acl = :private` that CW figures I need to have signed URLs even though I don't because I have Signed Cookies active.

**Comment by sorentwo** [comment]
Using `aws_signer` only effects CloudFront. You'll still get signed URLs when `aws_acl` is set to `:private`, as you mentioned. You can change them to public, but you'll need to change the bucket policy to match.

**Comment by jasper502** [comment]
Thanks of the feedback.  Any idea why I loose my asset_host?

**Comment by sorentwo** [comment]
The `asset_host` isn't used for private assets, only for public assets and signed assets. You can see the conditions [within the url method](https://github.com/sorentwo/carrierwave-aws/blob/master/lib/carrierwave/storage/aws_file.rb#L70).

**Comment by cmalpeli** [comment]
@jasper502 did you ever figure out a way to use asset_host when the files are private?
