### ISSUE TITLE
Under load getting random uninitialized constant Aws::S3::Resource

### ISSUE THREAD

**Issue by peterjtracey** [sorentwo/carrierwave-aws#93]
In a class Medium:
`class Medium < ActiveRecord::Base`
I have an uploader:
`  mount_uploader :picture, PictureUploader, mount_on: :image`
and a property thumbnail_url:
`  def thumbnail_url
    picture.present? ? picture_url : image_url
  end`
When load testing, get:
uninitialized constant Aws::S3::Resource
deep within the carrierwave-aws gem:
…s/carrierwave-aws-1.0.1/lib/carrierwave/storage/
aws.rb:  26:in `connection'

only for about .05% of requests. The errors go away completely after a little while of running under load. They only happen at the very start of the tests. They happen when accessing the property thumbnail_url.

**Comment by sorentwo** [comment]
This is coming from `aws-sdk-resources`, which is using `autoload`. I've pushed a commit that eagerly loads 'S3', and should fix this. The link referenced in the commit explains the threading situation that causes this, and how the workaround fixes it.

**Comment by sorentwo** [comment]
I've release `v1.0.2` to combat this issue. Thanks for reporting it!
