### ISSUE TITLE
Why asset_host isn't used for private assets?

### ISSUE THREAD

**Issue by tomomura** [sorentwo/carrierwave-aws#94]

**Comment by sorentwo** [comment]
This would have been more appropriate as a comment on #90, or at least have a some additional context. Truthfully I don't remember why it isn't used for private assets, it was modeled after the way fog handled urls. Is this causing trouble for you?

**Comment by tomomura** [comment]
I using CloudFront [origin access identity](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) for restrict bucket access.
And, Object upload from ec2 instance was granted `IAM Roles`.
Then, I want to uploaded S3 object ACL is private.

**Comment by sorentwo** [comment]
I don't have a use case for private asset host, so I can't easily verify any changes. If you would like to make the change and test it out I will gladly accept a pull request.
