### ISSUE TITLE
Wrong urls.

### ISSUE THREAD

**Issue by davidwessman** [sorentwo/carrierwave-aws#95]
When uploading files, they produce an url like:
- `https://**myapp**.s3.eu-central-1.amazonaws.com/uploads/file.pdf`

However, my S3 links are now days:
- `https://s3.eu-central-1.amazonaws.com/**myapp**/uploads/file.pdf`

Any clue how to patch this?

**Comment by sorentwo** [comment]
If I recall this is based on the actual name of your app. If there are periods in the name it can't use the subdomain version. The URL is built by aws-sdk and not by carrierwave-aws, so if you need more information please read their official documentation.
