### ISSUE TITLE
Support for server-side encryption headers

### ISSUE THREAD

**Issue by leesmith** [sorentwo/carrierwave-aws#99]
Does this gem support server-side encryption headers like what the AWS docs are referring to? Thanks.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

https://docs.aws.amazon.com/AmazonS3/latest/dev/SSEUsingRubySDK.html

**Comment by sorentwo** [comment]
I've never tried using SSE, but carrierwave-aws will pass any custom attributes through to aws-sdk, which I imagine would include the necessary headers. Set options with `config.aws_attributes = { server_side_encryption: :aes256 }`, or whatever you need.

**Comment by leesmith** [comment]
Thanks for the reply @sorentwo! 👊 

Also, if it helps anyone else, here's how I had to specify the encryption:

```
config.aws_attributes = {
  server_side_encryption: 'AES256'
}
```
